name: Validate Dockerfile

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate_dockerfile:
    uses: dariocurr/.github/.github/workflows/validate_dockerfile.yml@main
    with:
      dockerfile: ./.devcontainer/Dockerfile
      from: dev
      to: main
